# specify a directory to install
cask_args appdir: '/Applications'

brew 'cmake'
brew 'coreutils'

brew 'bat'
brew 'direnv'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'jq'
brew 'ripgrep'
brew 'zoxide'

brew 'asdf'
brew 'fish'
brew 'opencode'
brew 'starship'

brew 'yazi'
brew 'ffmpeg-full'
brew 'imagemagick-full'
brew 'poppler'
brew 'resvg'
brew 'sevenzip'
cask 'font-symbols-only-nerd-font'

cask 'caffeine'
cask 'claude-code'
cask 'docker'
cask 'ghostty'
cask 'insomnia'
cask 'kap'
cask 'notion'
cask 'raycast'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
