# specify a directory to install
cask_args appdir: '/Applications'

brew 'cmake'
brew 'coreutils'
brew 'fzf'
brew 'vim'
brew 'autojump'
brew 'asdf'
brew 'fish'

cask 'caffeine'
cask 'docker'
cask 'insomnia'
cask 'licecap'
cask 'postico'
cask 'notion'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'
