#!/bin/bash

# Dotfiles vars
export DOTFILES="${HOME}/.dotfiles"
export DOTFILES_CONFIGS_DIR="${DOTFILES}/configs"
export RUBY_VERSION="2.6.0"
export ERLANG_VERSION="21.0.5"
export ELIXIR_VERSION="1.7.4"


####################################################################
# Configuring the shell
####################################################################

echo "Installing Oh my ZSH..."

if ![ -d "$HOME"/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  
  echo "Done!"
else
  echo "ZSH is already installed!"
fi

# Use ZSH as shell
chsh -s /bin/zsh

# Iterm2 integration
curl -Ls https://iterm2.com/misc/zsh_startup.in -o ${HOME}/.iterm2_shell_integration.zsh

echo "Installing ZSH pure prompt..."
npm install --global pure-prompt

# Create symbolic links
ln -sf ${DOTFILES_CONFIGS_DIR}/zshrc ~/.zshrc

echo "Shell configured!"

####################################################################
# Configuring iTerm2
####################################################################

echo "Setting iterm2 preferences folder..."
# defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "~/dotfiles/iterm"
# defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true
echo "iTerm2 configured!"

####################################################################
# Configuring Git
####################################################################

echo "Configuring Git..."
echo "Moving configuration files..."

ln -sf ${DOTFILES_CONFIGS_DIR}/gitconfig ~/.gitconfig
ln -sf ${DOTFILES_CONFIGS_DIR}/gitignore ~/.gitignore
ln -sf ${DOTFILES_CONFIGS_DIR}/gitmessage ~/.gitmessage

echo "Done!"

####################################################################
# Configuring Ruby
####################################################################

echo "Configuring Ruby..."

if rbenv version 2>/dev/null; then  
  ln -sf ${DOTFILES_CONFIGS_DIR}/gemrc ~/.gemrc
  ln -sf ${DOTFILES_CONFIGS_DIR}/railsrc ~/.railsrc

  # Create default file to irb history
  touch ~/.irb-history

  echo "Installing ruby versions..."
  rbenv install ${RUBY_VERSION}
  rbenv global ${RUBY_VERSION}
  echo "Ruby ${RUBY_VERSION} installed correctly!"

else
  echo "Ruby is already configured!"
fi

####################################################################
# Configuring Erlang/Elixir
####################################################################

echo "Configuring Elixir..."
echo "Installing asdf..."

if asdf version 2>/dev/null; then  
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.3

  echo "Configuring asdf..."

  echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
  echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc

  echo "Adding asdf plugins..."
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git

  echo "Installing Erlang versions..."
  asdf install erlang ${ERLANG_VERSION}

  echo "Installing Elixir versions..."
  asdf install elixir ${ELIXIR_VERSION}

  echo "Erlang ${ERLANG_VERSION} and Elixir ${ELIXIR_VERSION} installed correctly!"

else
  echo "Skipping installation, Elixir is already installed"
fi

####################################################################
# Setup src/ directory
####################################################################

echo "Creating src directory..."
mkdir -p ~/src/private


####################################################################
# Last steps
####################################################################

echo "Done :)"
