# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set empty theme to use pure ZSH
ZSH_THEME=""

# Which plugins would you like to load? Plugins can be found in:
# #   ~/.oh-my-zsh/plugins/*
# #
# # Custom plugins may be added to:
# #   ~/.oh-my-zsh/custom/plugins/
# #
# # Example format:
# #   plugins=(rails git textmate ruby)
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# pure ZSH
autoload -U promptinit; promptinit
prompt pure

# Loading our .dotfiles (aliases, functions, exports, extras)
# ~/.extra can be used for settings you don't want to commit.
for file in ~/.dotfiles/shell/*; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# autojump
[[ -s /usr/local/etc/profile.d/autojump.sh ]] && . /usr/local/etc/profile.d/autojump.sh